version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz

brews:
  - repository:
      owner: robinjoseph08
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/robinjoseph08/wktr
    description: Manage git worktrees with tmux integration
    license: MIT
    install: |
      bin.install "wktr"
